version: '3.1'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    hostname: clickhouse
    restart: always
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/var/lib/clickhouse 
      - ./initdb:/docker-entrypoint-initdb.d
      - ./conf/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/config.xml:/etc/clickhouse-server/config.xml
      - ./logs:/var/log/clickhouse-server
    networks:
      - ch_net

networks:
  ch_net:
    external:
      name: clickhouse_net