version: '3.1'
services:
  clickhouse:
    image: koray2021/clickhouse:22.8.19-amd64
    container_name: clickhouse
    hostname: clickhouse
    restart: always
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/var/lib/clickhouse 
      - ./conf/users.xml:/opt/bitnami/clickhouse/etc/users.xml 
      - ./conf/config.xml:/opt/bitnami/clickhouse/etc/config.xml  
      - ./logs:/opt/bitnami/clickhouse/logs
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - CLICKHOUSE_ADMIN_USER=${user}
      - CLICKHOUSE_ADMIN_PASSWORD=${passwd}
    networks:
        default:
            ipv4_address: 192.168.5.50

networks:
  default:
    external: true
    name: unite_net